events {
    worker_connections 1024;
}

http {
    # En-têtes de sécurité
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    upstream user-service {
        server user-service:3001;
    }

    upstream book-service {
        server book-service:3002;
    }

    upstream loan-service {
        server loan-service:3003;
    }

    server {
        listen 80;

        # Health check global
        location /health {
            return 200 '{"status":"OK","gateway":"nginx"}';
            add_header Content-Type application/json;
        }

        # Routes vers User Service
        location /api/users {
            proxy_pass http://user-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Routes vers Book Service
        location /api/books {
            proxy_pass http://book-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Routes vers Loan Service
        location /api/loans {
            proxy_pass http://loan-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}